apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spbtemplate.fullname" . }}
  labels:
    version: {{ .Values.image.tag | quote }}
    api: {{ .Values.labels.api }}
    tier: backend
    heritage: {{ .Release.Service }}
    chart: {{ template "spbtemplate.chart" . }}
    app: {{ template "spbtemplate.app" . }}
    env: {{ .Release.Namespace }}
type: Opaque
data:
  secret.yaml: {{ include "spbtemplate.secretData" . | b64enc }}